<?php

/**
 * This is the model base class for the table "centers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Centers".
 *
 * Columns in table "centers" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $center_id
 * @property string $center_code
 * @property string $location
 *
 */
abstract class BaseCenters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'centers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Centers|Centers', $n);
	}

	public static function representingColumn() {
		return 'center_code';
	}

	public function rules() {
		return array(
			array('center_code, location', 'required'),
			array('center_code', 'length', 'max'=>3),
			array('location', 'length', 'max'=>30),
			array('center_id, center_code, location', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'center_id' => Yii::t('app', 'Center'),
			'center_code' => Yii::t('app', 'Center Code'),
			'location' => Yii::t('app', 'Location'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('center_id', $this->center_id, true);
		$criteria->compare('center_code', $this->center_code, true);
		$criteria->compare('location', $this->location, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}